### ISSUE TITLE
How to enable golang code in Q50 3G watches?

### ISSUE THREAD

**Issue by KanybekMomukeyev** [avkspog/Q50RT#1]
Hi, thanks for sharing source codes.
How to enable golang code in Q50 3G watches? Where i can find technical details?
Could we write own web servers connection?

**Comment by avkspog** [comment]
Hi, Q50RT is a tcp server witch receive telemetry from the Q50 watch. TCP server host and port are confugured via SMS command to the device. The Q50RT server and a web server are in development. You can use these source codes fluently.

**Comment by KanybekMomukeyev** [comment]
@avkspog thank you very much, very helpfull details, will try it
